// apps/vue-app/src/App.vue
<template>
  <div id="app">
    <nav class="navbar">
      <div class="nav-brand">
        <h1>Vue App with Authdog</h1>
      </div>
      <div class="nav-links">
        <router-link to="/">Home</router-link>
        <router-link to="/profile" v-if="isAuthenticated">Profile</router-link>
        <router-link to="/login" v-if="!isAuthenticated">Login</router-link>
        <button @click="handleSignOut" v-if="isAuthenticated" class="sign-out-btn">
          Sign Out
        </button>
      </div>
    </nav>
    
    <main class="main-content">
      <AuthdogProvider>
        <router-view />
      </AuthdogProvider>
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useSession, useSignOut } from '@authdog/vue'
import { AuthdogProvider } from '@authdog/vue/client'

const { session } = useSession()
const { signOut } = useSignOut()

const isAuthenticated = computed(() => session.isAuthenticated)

const handleSignOut = async () => {
  await signOut()
}
</script>

<style scoped>
.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem 2rem;
  background-color: #f8f9fa;
  border-bottom: 1px solid #e9ecef;
}

.nav-brand h1 {
  margin: 0;
  color: #333;
}

.nav-links {
  display: flex;
  gap: 1rem;
  align-items: center;
}

.nav-links a {
  text-decoration: none;
  color: #007bff;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  transition: background-color 0.2s;
}

.nav-links a:hover {
  background-color: #e9ecef;
}

.sign-out-btn {
  background-color: #dc3545;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.2s;
}

.sign-out-btn:hover {
  background-color: #c82333;
}

.main-content {
  padding: 2rem;
}
</style>

// examples/angular/src/app/app.component.ts
import { Component, inject } from "@angular/core";
import { RouterLink, RouterOutlet } from "@angular/router";
import { AuthdogService } from "@authdog/angular";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [RouterOutlet, RouterLink],
  template: `
    <nav class="navbar">
      <a routerLink="/" class="brand">ACME Corp</a>

      <div class="links">
        <a routerLink="/">Home</a>
        @if (auth.isAuthenticated()) {
          <a routerLink="/profile">Profile</a>
        }

        @if (auth.isLoading()) {
          <span class="muted">Loading…</span>
        } @else if (auth.token()) {
          <button class="btn danger" (click)="auth.signOut()">Sign out</button>
        } @else {
          <button class="btn" (click)="auth.signIn()">Sign in</button>
        }
      </div>
    </nav>

    <main class="content">
      <router-outlet />
    </main>
  `,
  styles: [
    `
      .navbar {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 1rem 2rem;
        border-bottom: 1px solid var(--border);
        background: var(--surface);
      }
      .brand {
        font-weight: 700;
        font-size: 1.1rem;
        color: var(--fg);
      }
      .brand:hover {
        text-decoration: none;
      }
      .links {
        display: flex;
        gap: 1rem;
        align-items: center;
      }
      .muted {
        color: var(--muted);
      }
      .btn {
        border: none;
        border-radius: 6px;
        padding: 0.5rem 1rem;
        background: var(--primary);
        color: #fff;
        font-weight: 500;
      }
      .btn:hover {
        background: var(--primary-hover);
      }
      .btn.danger {
        background: var(--danger);
      }
      .content {
        max-width: 720px;
        margin: 0 auto;
        padding: 2rem;
      }
    `,
  ],
})
export class AppComponent {
  protected readonly auth = inject(AuthdogService);
}
