// packages/solid/src/provider.ts
import {
  createComponent,
  createContext,
  createSignal,
  onMount,
  type Accessor,
  type JSX,
} from "solid-js";
import { getPublicKeyPayload } from "./commons";
import { JWT_PATTERN, TOKEN_STORAGE_KEY } from "./session";

/** The reactive authentication context shared through {@link AuthdogProvider}. */
export interface AuthdogContextValue {
  /** The current session token, or `null`. */
  token: Accessor<string | null>;
  /** Whether the client is still bootstrapping the token on first load. */
  isLoading: Accessor<boolean>;
  /** Whether a token is present. Presence only — treat as a UI hint. */
  isAuthenticated: Accessor<boolean>;
  /** Persists (or clears) the token and updates reactive state. */
  setToken: (token: string | null) => void;
  /** The configured public key (`pk_…`). */
  publicKey: string;
}

export const AuthdogContext = createContext<AuthdogContextValue>();

export interface AuthdogProviderProps {
  /** The Authdog public key (`pk_…`). Safe to expose to the browser. */
  publicKey: string;
  children?: JSX.Element;
}

/**
 * Provides the reactive Authdog auth context to descendant components.
 *
 * The public key is validated once at construction (enforcing the trusted
 * identity-host allowlist). On mount (browser only) it consumes a `?token=`
 * from the URL — persisting JWT-shaped values to `localStorage` and reloading
 * so the server sees the token — otherwise it hydrates from `localStorage`.
 */
export function AuthdogProvider(props: AuthdogProviderProps): JSX.Element {
  // Validate + parse eagerly so an invalid/untrusted key throws at startup.
  getPublicKeyPayload(props.publicKey);

  const [token, setTokenSignal] = createSignal<string | null>(null);
  const [isLoading, setIsLoading] = createSignal(true);

  const setToken = (next: string | null) => {
    setTokenSignal(next);
    if (typeof window === "undefined") return;
    if (next === null) {
      window.localStorage.removeItem(TOKEN_STORAGE_KEY);
    } else {
      window.localStorage.setItem(TOKEN_STORAGE_KEY, next);
    }
  };

  onMount(() => {
    if (typeof window === "undefined") {
      setIsLoading(false);
      return;
    }

    const url = new URL(window.location.href);
    const urlToken = url.searchParams.get("token");

    if (urlToken) {
      // Always strip the token from the URL, valid or not.
      url.searchParams.delete("token");
      window.history.replaceState({}, document.title, url.toString());

      if (JWT_PATTERN.test(urlToken)) {
        setToken(urlToken);
        window.location.reload();
        return;
      }
    }

    const existing = window.localStorage.getItem(TOKEN_STORAGE_KEY);
    if (existing) {
      setTokenSignal(existing);
    }
    setIsLoading(false);
  });

  const value: AuthdogContextValue = {
    token,
    isLoading,
    isAuthenticated: () => !!token(),
    setToken,
    publicKey: props.publicKey,
  };

  return createComponent(AuthdogContext.Provider, {
    value,
    get children() {
      return props.children;
    },
  });
}

// packages/react/src/provider.tsx
import {
  createContext,
  useCallback,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import {
  JWT_PATTERN,
  TOKEN_STORAGE_KEY,
  TOKEN_UPDATED_EVENT,
} from "./constants";

export interface AuthdogContextValue {
  publicKey: string;
  token: string | null;
  isLoading: boolean;
  setToken: (token: string | null) => void;
}

export const AuthdogContext = createContext<AuthdogContextValue | null>(null);

export interface AuthdogProviderProps {
  publicKey: string;
  children?: ReactNode;
  /**
   * When true (default), capture `?token=` from the URL into localStorage and
   * strip it from the address bar.
   */
  captureTokenFromUrl?: boolean;
}

export const AuthdogProvider = ({
  publicKey,
  children,
  captureTokenFromUrl = true,
}: AuthdogProviderProps) => {
  const [token, setTokenState] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  const setToken = useCallback((value: string | null) => {
    if (typeof window === "undefined") {
      setTokenState(value);
      return;
    }
    if (value) {
      window.localStorage.setItem(TOKEN_STORAGE_KEY, value);
    } else {
      window.localStorage.removeItem(TOKEN_STORAGE_KEY);
    }
    setTokenState(value);
    window.dispatchEvent(new Event(TOKEN_UPDATED_EVENT));
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") {
      setIsLoading(false);
      return;
    }

    if (captureTokenFromUrl) {
      const params = new URLSearchParams(window.location.search);
      const urlToken = params.get("token");
      if (urlToken) {
        if (JWT_PATTERN.test(urlToken)) {
          window.localStorage.setItem(TOKEN_STORAGE_KEY, urlToken);
          setTokenState(urlToken);
        }
        params.delete("token");
        const next = `${window.location.pathname}${
          params.toString() ? `?${params.toString()}` : ""
        }${window.location.hash}`;
        window.history.replaceState({}, document.title, next || "/");
        window.dispatchEvent(new Event(TOKEN_UPDATED_EVENT));
        setIsLoading(false);
        return;
      }
    }

    setTokenState(window.localStorage.getItem(TOKEN_STORAGE_KEY));
    setIsLoading(false);
  }, [captureTokenFromUrl]);

  useEffect(() => {
    if (typeof window === "undefined") return;

    const sync = () => {
      setTokenState(window.localStorage.getItem(TOKEN_STORAGE_KEY));
    };

    const onStorage = (event: StorageEvent) => {
      if (event.key === TOKEN_STORAGE_KEY) sync();
    };

    window.addEventListener(TOKEN_UPDATED_EVENT, sync);
    window.addEventListener("storage", onStorage);
    return () => {
      window.removeEventListener(TOKEN_UPDATED_EVENT, sync);
      window.removeEventListener("storage", onStorage);
    };
  }, []);

  const value = useMemo(
    () => ({ publicKey, token, isLoading, setToken }),
    [publicKey, token, isLoading, setToken],
  );

  return (
    <AuthdogContext.Provider value={value}>{children}</AuthdogContext.Provider>
  );
};
